version: "2.0"
services:
  pagermaid:
    image: teampgm/pagermaid_modify:latest
    restart: always
    container_name: pagermaid
    hostname: pagermaid
    volumes:
      - ./data:/pagermaid/workdir/data
      - ./plugins:/pagermaid/workdir/plugins
    environment:
